/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "league-card-generator-app": {
      type: "sst.aws.React";
      url: string;
    };
    "league-card-generator-handler": {
      name: string;
      type: "sst.aws.Function";
      url: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import "sst";
export {};
